"""update carFK

Revision ID: a3ea3646f8a5
Revises: 8af31fa8b989
Create Date: 2025-05-30 02:38:33.511646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3ea3646f8a5'
down_revision: Union[str, None] = '8af31fa8b989'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car_rentals', sa.Column('car_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'car_rentals', 'cars', ['car_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'car_rentals', type_='foreignkey')
    op.drop_column('car_rentals', 'car_id')
    # ### end Alembic commands ###
